package sdid.cli;

import java.util.Map;
import javax.xml.ws.*;
import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import pt.ulisboa.tecnico.sdis.id.ws.*; // classes generated by wsimport from WSDL


public class SDIDClient {

    public static void main(String[] args) {
        SDId_Service service = new SDId_Service();
        SDId port = service.getSDIdImplPort();

        BindingProvider bindingProvider = (BindingProvider) port;
        Map<String, Object> requestContext = bindingProvider.getRequestContext();

        try {
            String url = args[0];
            requestContext.put(ENDPOINT_ADDRESS_PROPERTY, url);
            System.out.printf("Remote call to %s ...%n", url);
            
            port.createUser("Ola1234", "ola@gmail.com");
        }
        
        catch (Exception e) {
        	e.printStackTrace();
        }

    }

}
